export const SET_INITIAL_ENTRIES_STARTED = 'ENTRIES/SET_INITIAL_ENTRIES_STARTED';
export const SET_INITIAL_ENTRIES_SUCCESS = 'ENTRIES/SET_INITIAL_ENTRIES_SUCCESS';
export const SET_INITIAL_ENTRIES_ENDED = 'ENTRIES/SET_INITIAL_ENTRIES_ENDED';

export const SET_INITIAL_YEARS = 'YEARS/SET_INITIAL_YEARS';
export const SET_INITIAL_STEPS = 'STEPS/SET_INITIAL_STEPS';