# Generated by Django 2.2.12 on 2021-11-06 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_conteststep_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Порядок выступления'),
        ),
    ]
