# Generated by Django 2.2.12 on 2021-11-06 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_entry_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='score',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2, null=True, verbose_name='Счет'),
        ),
    ]
