# Generated by Django 2.2.12 on 2021-11-06 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20211106_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='year',
            field=models.IntegerField(default=0, verbose_name='Год выступления'),
        ),
    ]
