# Generated by Django 2.2.12 on 2021-11-06 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_entry_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='qualified',
            field=models.BooleanField(default=False, verbose_name='Финалист'),
        ),
    ]
