# Generated by Django 2.2.12 on 2021-11-14 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_entry_qualified'),
    ]

    operations = [
        migrations.CreateModel(
            name='Star',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purity', models.BooleanField(default=False, verbose_name='Чистота исполнения песни')),
                ('show', models.BooleanField(default=False, verbose_name='Наличие шоу в выступлении')),
                ('difficulty', models.BooleanField(default=False, verbose_name='Сложность исполнения песни')),
                ('originality', models.BooleanField(default=False, verbose_name='Оригинальность исполнения песни')),
                ('sympathy', models.BooleanField(default=False, verbose_name='Личная симпатия')),
            ],
        ),
        migrations.AlterField(
            model_name='entry',
            name='score',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main_app.Star', verbose_name='Оценка'),
        ),
    ]
