# Generated by Django 2.2.12 on 2021-11-14 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_auto_20211114_2320'),
    ]

    operations = [
        migrations.RenameField(
            model_name='star',
            old_name='sympathy',
            new_name='sympath',
        ),
    ]
