# Generated by Django 2.2.12 on 2021-11-14 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_auto_20211114_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='score',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2, verbose_name='Оценка'),
            preserve_default=False,
        ),
    ]
