# Generated by Django 2.2.12 on 2021-11-15 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_auto_20211114_2331'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Страна исполнителя')),
            ],
        ),
        migrations.AlterField(
            model_name='artist',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main_app.Country', verbose_name='Страна исполнителя'),
        ),
    ]
