# Generated by Django 2.2.12 on 2021-11-16 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_auto_20211116_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='difficulty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='Сложность исполнения песни'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='originality',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='Оригинальность исполнения песни'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='purity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='Чистота исполнения песни'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='show',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='Наличие шоу в выступлении'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='sympathy',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='Личная симпатия'),
        ),
    ]
