# Generated by Django 2.2.12 on 2021-12-10 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0018_auto_20211210_0051'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='place',
            field=models.IntegerField(default=0, null=True, verbose_name='Место участника'),
        ),
    ]
