# Generated by Django 2.2.12 on 2021-12-11 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_entry_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='test_field',
            field=models.IntegerField(default=0, verbose_name='Порядок выступления'),
        ),
    ]
