# Generated by Django 2.2.12 on 2021-12-12 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0020_entry_test_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='test_field',
        ),
    ]
